# Generated by Django 4.0.1 on 2022-01-28 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDataForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=200)),
                ('lName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('webaddress', models.CharField(max_length=200)),
                ('whatsappnumber', models.CharField(max_length=25)),
                ('bestway', models.CharField(max_length=200)),
                ('agentType', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='CommonFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=200)),
                ('lName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=1000)),
                ('phone', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='LookingTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourName', models.CharField(max_length=200)),
                ('studentName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=200)),
                ('medium', models.CharField(max_length=40)),
                ('requirements', models.TextField(max_length=800, null=True)),
                ('Class', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.commonfields')),
                ('profilephoto', models.ImageField(default=None, upload_to='AdmissionForm')),
                ('passportno', models.CharField(blank=True, max_length=40, null=True)),
                ('passportExpireDate', models.CharField(blank=True, max_length=40, null=True)),
                ('nationality', models.CharField(max_length=40)),
                ('nID_birthNumber', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=40)),
                ('dateofbirth', models.DateField()),
                ('placeofbirth', models.CharField(max_length=40)),
                ('maritalstatus', models.CharField(max_length=40)),
                ('homeaddress', models.CharField(max_length=40)),
                ('homephone', models.CharField(max_length=40)),
                ('applyuniveristy', models.CharField(max_length=40)),
                ('majorsub', models.CharField(max_length=40)),
                ('profession', models.CharField(max_length=40)),
                ('language', models.CharField(max_length=40)),
                ('fathername', models.CharField(max_length=40)),
                ('mothername', models.CharField(max_length=40)),
                ('fatheremployement', models.CharField(max_length=40)),
                ('motheremployement', models.CharField(max_length=40)),
                ('fathernumber', models.CharField(max_length=40)),
                ('mothernumber', models.CharField(max_length=40)),
                ('academiccertificate', models.FileField(blank=True, default=None, null=True, upload_to='AdmissionForm')),
                ('transcript', models.FileField(blank=True, default=None, null=True, upload_to='AdmissionForm')),
                ('academiccertificate2', models.FileField(blank=True, default=None, null=True, upload_to='AdmissionForm')),
                ('transcript2', models.FileField(blank=True, default=None, null=True, upload_to='AdmissionForm')),
                ('academiccertificate3', models.FileField(blank=True, default=None, null=True, upload_to='AdmissionForm')),
                ('transcript3', models.FileField(blank=True, default=None, null=True, upload_to='AdmissionForm')),
                ('academiccertificate4', models.FileField(blank=True, default=None, null=True, upload_to='AdmissionForm')),
                ('transcript4', models.FileField(blank=True, default=None, null=True, upload_to='AdmissionForm')),
                ('academiccertificate5', models.FileField(blank=True, default=None, null=True, upload_to='AdmissionForm')),
                ('transcript5', models.FileField(blank=True, default=None, null=True, upload_to='AdmissionForm')),
                ('passportscan', models.FileField(blank=True, default=None, null=True, upload_to='AdmissionForm')),
                ('nIDscan', models.FileField(blank=True, default=None, null=True, upload_to='AdmissionForm')),
                ('bankstatement', models.FileField(blank=True, default=None, null=True, upload_to='AdmissionForm')),
                ('recommendationletter', models.FileField(blank=True, default=None, null=True, upload_to='AdmissionForm')),
                ('recommendationletter2', models.FileField(blank=True, default=None, null=True, upload_to='AdmissionForm')),
                ('recommendationletter3', models.FileField(blank=True, default=None, null=True, upload_to='AdmissionForm')),
                ('studyplan', models.FileField(blank=True, default=None, null=True, upload_to='AdmissionForm')),
            ],
            bases=('form.commonfields',),
        ),
        migrations.CreateModel(
            name='BecomeTutor',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.commonfields')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('degreeobtained', models.CharField(max_length=70)),
                ('EducationOrganization', models.CharField(max_length=70)),
                ('EducationBackground', models.CharField(max_length=70)),
                ('gender', models.CharField(max_length=40)),
                ('tuitionarea', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=40)),
                ('confirmpassword', models.CharField(max_length=40)),
            ],
            bases=('form.commonfields',),
        ),
        migrations.CreateModel(
            name='BusinessAgent',
            fields=[
                ('agentdataform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.agentdataform')),
                ('businessName', models.CharField(max_length=100)),
                ('tradeNum', models.CharField(max_length=100)),
                ('businessAddress', models.CharField(max_length=200)),
                ('businessNum', models.CharField(max_length=25)),
                ('businessemail', models.CharField(max_length=200)),
                ('agentphoto', models.ImageField(upload_to='agentphotos')),
                ('agentnid', models.FileField(upload_to='agentnID')),
                ('tradelicense', models.FileField(upload_to='trade')),
                ('tinbin', models.FileField(upload_to='tin')),
            ],
            bases=('form.agentdataform',),
        ),
        migrations.CreateModel(
            name='CommonForm',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.commonfields')),
                ('studyLevel', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('counselMode', models.CharField(max_length=25)),
            ],
            bases=('form.commonfields',),
        ),
        migrations.CreateModel(
            name='DevelopingSkills',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.commonfields')),
                ('counselMode', models.CharField(max_length=40)),
                ('skill', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
            ],
            bases=('form.commonfields',),
        ),
        migrations.CreateModel(
            name='IndivisualAgent',
            fields=[
                ('agentdataform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.agentdataform')),
                ('occupation', models.CharField(max_length=100)),
                ('agentphoto', models.ImageField(upload_to='agentphotos')),
                ('agentnid', models.FileField(upload_to='agentnID')),
                ('academicCertificate', models.FileField(upload_to='academic')),
            ],
            bases=('form.agentdataform',),
        ),
        migrations.CreateModel(
            name='LanguageProficiency',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.commonfields')),
                ('counselMode', models.CharField(max_length=40)),
                ('language', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
            ],
            bases=('form.commonfields',),
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.commonfields')),
                ('studywhen', models.CharField(max_length=100)),
                ('studycountry', models.CharField(max_length=100)),
                ('counselMode', models.CharField(max_length=40)),
                ('studyLevel', models.CharField(max_length=40)),
            ],
            bases=('form.commonfields',),
        ),
    ]
