# Generated by Django 4.0 on 2022-01-19 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=200)),
                ('lName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=1000)),
                ('phone', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='LookingTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourName', models.CharField(max_length=200)),
                ('studentName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=200)),
                ('medium', models.CharField(max_length=40)),
                ('requirements', models.TextField(max_length=800)),
                ('Class', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AgentDataForm',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.commonfields')),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('websiteaddress', models.CharField(max_length=200)),
                ('bestway', models.CharField(max_length=200)),
                ('agentphoto', models.ImageField(upload_to='agentphotos')),
                ('nID', models.FileField(upload_to='agentnID')),
                ('passport', models.FileField(upload_to='agentnPassport')),
            ],
            bases=('form.commonfields',),
        ),
        migrations.CreateModel(
            name='BecomeTutor',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.commonfields')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('degreeobtained', models.CharField(max_length=70)),
                ('EducationOrganization', models.CharField(max_length=70)),
                ('EducationBackground', models.CharField(max_length=70)),
                ('gender', models.CharField(max_length=40)),
                ('tuitionarea', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=40)),
                ('confirmpassword', models.CharField(max_length=40)),
            ],
            bases=('form.commonfields',),
        ),
        migrations.CreateModel(
            name='DevelopingSkills',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.commonfields')),
                ('counselMode', models.CharField(max_length=40)),
                ('skill', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
            ],
            bases=('form.commonfields',),
        ),
        migrations.CreateModel(
            name='LanguageProficiency',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.commonfields')),
                ('counselMode', models.CharField(max_length=40)),
                ('language', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
            ],
            bases=('form.commonfields',),
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.commonfields')),
                ('studywhen', models.CharField(max_length=100)),
                ('studycountry', models.CharField(max_length=100)),
                ('counselMode', models.CharField(max_length=40)),
                ('studyLevel', models.CharField(max_length=40)),
            ],
            bases=('form.commonfields',),
        ),
        migrations.CreateModel(
            name='BusinessAgent',
            fields=[
                ('agentdataform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.agentdataform')),
                ('businessNum', models.CharField(max_length=25)),
                ('businessemail', models.CharField(max_length=200)),
                ('businessAddress', models.CharField(max_length=200)),
            ],
            bases=('form.agentdataform',),
        ),
    ]
