# Generated by Django 4.0 on 2022-02-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdataform',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agentdataform',
            name='phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
