# Generated by Django 4.0.1 on 2022-01-18 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=200)),
                ('lName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageProficiency',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.commonfields')),
                ('counselMode', models.CharField(max_length=40)),
                ('language', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
            ],
            bases=('form.commonfields',),
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.commonfields')),
                ('studywhen', models.CharField(max_length=100)),
                ('studycountry', models.CharField(max_length=100)),
                ('counselMode', models.CharField(max_length=40)),
                ('studyLevel', models.CharField(max_length=40)),
            ],
            bases=('form.commonfields',),
        ),
    ]
