# Generated by Django 4.0.1 on 2022-01-19 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_commonfields_languageproficiency_scholarship'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopingSkills',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.commonfields')),
                ('counselMode', models.CharField(max_length=40)),
                ('skill', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
            ],
            bases=('form.commonfields',),
        ),
    ]
