# Generated by Django 4.0.1 on 2022-01-19 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_developingskills'),
    ]

    operations = [
        migrations.CreateModel(
            name='BecomeTutor',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.commonfields')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('degreeobtained', models.CharField(max_length=70)),
                ('EducationOrganization', models.CharField(max_length=70)),
                ('EducationBackground', models.CharField(max_length=70)),
                ('gender', models.CharField(max_length=40)),
                ('tuitionarea', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=40)),
                ('confirmpassword', models.CharField(max_length=40)),
            ],
            bases=('form.commonfields',),
        ),
        migrations.CreateModel(
            name='LookingTutor',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.commonfields')),
                ('address', models.CharField(max_length=200)),
                ('medium', models.CharField(max_length=40)),
                ('requirements', models.TextField(max_length=800)),
                ('Class', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
            ],
            bases=('form.commonfields',),
        ),
        migrations.DeleteModel(
            name='AgentDataForm',
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
