# Generated by Django 4.0.1 on 2022-01-19 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_becometutor_lookingtutor_delete_agentdataform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDataForm',
            fields=[
                ('commonfields_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.commonfields')),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('websiteaddress', models.CharField(max_length=200)),
                ('bestway', models.CharField(max_length=200)),
                ('agentphoto', models.ImageField(upload_to='agentphotos')),
                ('nID', models.FileField(upload_to='agentnID')),
                ('passport', models.FileField(upload_to='agentnPassport')),
            ],
            bases=('form.commonfields',),
        ),
        migrations.CreateModel(
            name='BusinessAgent',
            fields=[
                ('agentdataform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='form.agentdataform')),
                ('businessNum', models.CharField(max_length=25)),
                ('businessemail', models.CharField(max_length=200)),
                ('businessAddress', models.CharField(max_length=200)),
            ],
            bases=('form.agentdataform',),
        ),
    ]
