# Generated by Django 4.0.2 on 2022-02-17 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='richeditor',
            name='pgName',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='richeditor',
            name='img',
            field=models.ImageField(default=None, upload_to='Pages'),
        ),
    ]
