# Generated by Django 4.0 on 2021-12-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=200)),
                ('lName', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('countryCode', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=15)),
                ('counsellingMode', models.CharField(max_length=20)),
                ('studyLevel', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
