# Generated by Django 4.0 on 2022-01-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformdata',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
