# Generated by Django 4.0 on 2021-12-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactForm', '0002_rename_employee_formdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdata',
            old_name='counsellingMode',
            new_name='counselingMode',
        ),
    ]
